---

- name: Create installer tftp directory
  file:
    path: '{{ ipxe_tftp_root }}/{{ item.distro }}-installer/{{ item.release }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_items:
    - '{{ ipxe_debian_pxeboot_dists }}'

- name: Download Debian netboot installer
  get_url:
    url: 'http://{{ item.0.mirror }}/{{ item.0.distro }}/dists/{{ item.0.release }}/main/installer-amd64/current/images/netboot/{{ item.0.distro }}-installer/amd64/{{ item.1 }}'
    # dest: '{{ ipxe_debian_pxeboot_workdir }}/{{ item.0.name }}/{{ item.1 }}'
    dest: '{{ ipxe_tftp_root }}/{{ item.0.distro }}-installer/{{ item.0.release }}/{{ item.1 }}'
  with_nested:
    - '{{ ipxe_debian_pxeboot_dists }}'
    - [ 'linux', 'initrd.gz' ]

